export const mockDatabase = {
  students: [
    {
      documentType: "TI",
      name: "Martin ",
      lastname: "Cardenas ",
      profile_img: "https://i.ibb.co/wr9J45j/std9.jpg",
      number_identify: "12345678",
      password: "1234",
      dateOfBirth: "9/21/2009",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [4.5, 3.7, 5.0],
          final: 4.4,
          points: 440,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [5.4, 2.4, 6.7],
          final: 4.8,
          points: 480,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [0.8, 8.1, 2.5],
          final: 3.8,
          points: 380,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Santiago",
      lastname: "Lopez",
      profile_img: "",
      number_identify: "1210879048",
      password: "1234",
      dateOfBirth: "1/12/2009",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [3.7, 9.2, 6.1, 6.3],
          final: 6.3,
          points: 630,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [9.8, 9.3, 5.8, 8.3],
          final: 8.3,
          points: 830,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [9.2, 7.9, 8.3, 8.5],
          final: 8.5,
          points: 850,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Samuel",
      lastname: "Moreno",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1955429455",
      password: "1234",
      dateOfBirth: "11/16/2009",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [1.3, 6.0, 2.3, 3.2],
          final: 3.2,
          points: 320,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [8.0, 3.1, 1.0, 4.0],
          final: 4.0,
          points: 400,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [6.6, 3.6, 7.8, 6.0],
          final: 6.0,
          points: 600,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Gabriel",
      lastname: "Ramos",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1091766160",
      password: "1234",
      dateOfBirth: "5/21/2010",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [3.5, 4.7, 5.5, 4.6],
          final: 4.6,
          points: 459,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [2.4, 10.0, 0.4, 4.3],
          final: 4.3,
          points: 430,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [6.2, 2.1, 1.9, 3.4],
          final: 3.4,
          points: 340,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Sofia",
      lastname: "Diaz",
      profile_img: "https://i.ibb.co/gyZNM11/std5.jpg",
      number_identify: "654321",
      password: "1234",
      dateOfBirth: "7/5/2009",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [6.9, 7.7, 5.9, 6.8],
          final: 6.8,
          points: 680,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [6.1, 8.7, 6.3, 7.0],
          final: 7.0,
          points: 700,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [1.5, 8.1, 0.9, 3.5],
          final: 3.5,
          points: 350,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Isabel",
      lastname: "Gomez",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1476292370",
      password: "1234",
      dateOfBirth: "12/10/2010",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [1.5, 9.2, 8.1, 6.3],
          final: 6.3,
          points: 630,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [8.5, 7.2, 8.3, 8.0],
          final: 8.0,
          points: 800,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [1.9, 9.8, 0.6, 4.1],
          final: 4.1,
          points: 409,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Ana",
      lastname: "Rodriguez",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1331774265",
      password: "1234",
      dateOfBirth: "1/16/2011",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [5.4, 7.0, 0.6, 4.3],
          final: 4.3,
          points: 430,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [6.5, 0.9, 9.4, 5.6],
          final: 5.6,
          points: 560,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [3.1, 1.0, 3.9, 2.7],
          final: 2.7,
          points: 270,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Maria",
      lastname: "Diaz",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1051637990",
      password: "1234",
      dateOfBirth: "2/6/2009",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [7.8, 6.2, 5.8, 6.6],
          final: 6.6,
          points: 660,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [6.3, 6.9, 2.2, 5.1],
          final: 5.1,
          points: 509,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [9.8, 6.0, 7.2, 7.7],
          final: 7.7,
          points: 770,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Isabel",
      lastname: "Diaz",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1015222895",
      password: "1234",
      dateOfBirth: "12/9/2010",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [0.2, 1.1, 5.0, 2.1],
          final: 2.1,
          points: 210,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [2.7, 2.0, 4.4, 3.0],
          final: 3.0,
          points: 300,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [0.4, 5.1, 4.0, 3.2],
          final: 3.2,
          points: 320,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Luis",
      lastname: "Cardenas",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1467582497",
      password: "1234",
      dateOfBirth: "8/17/2011",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [8.2, 5.3, 8.4, 7.3],
          final: 7.3,
          points: 730,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [4.1, 4.0, 8.2, 5.4],
          final: 5.4,
          points: 540,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [2.7, 6.0, 6.1, 4.9],
          final: 4.9,
          points: 490,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Andrea",
      lastname: "Lopez",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1255620677",
      password: "1234",
      dateOfBirth: "11/13/2010",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [5.2, 8.8, 2.0, 5.3],
          final: 5.3,
          points: 530,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [7.3, 3.4, 1.4, 4.0],
          final: 4.0,
          points: 400,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [9.7, 5.3, 9.2, 8.1],
          final: 8.1,
          points: 810,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Gabriel",
      lastname: "Rodriguez",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1161238729",
      password: "1234",
      dateOfBirth: "12/22/2010",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [4.1, 1.8, 1.3, 2.4],
          final: 2.4,
          points: 240,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [8.4, 7.1, 8.7, 8.1],
          final: 8.1,
          points: 810,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [7.6, 9.2, 9.5, 8.8],
          final: 8.8,
          points: 880,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Lucia",
      lastname: "Rodriguez",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1263994925",
      password: "1234",
      dateOfBirth: "9/2/2011",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [7.6, 9.0, 7.5, 8.0],
          final: 8.0,
          points: 800,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [4.5, 4.4, 2.4, 3.8],
          final: 3.8,
          points: 380,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [2.1, 8.5, 8.0, 6.2],
          final: 6.2,
          points: 620,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Maria",
      lastname: "Hernandez",
      profile_img: "https://i.ibb.co/gyZNM11/std5.jpg",
      number_identify: "1234",
      password: "1234",
      dateOfBirth: "4/6/2009",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [0.7, 1.9, 9.0, 3.9],
          final: 3.9,
          points: 390,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [6.2, 1.4, 2.2, 3.3],
          final: 3.3,
          points: 330,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [4.2, 5.7, 8.3, 6.1],
          final: 6.1,
          points: 610,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Miguel",
      lastname: "Rodriguez",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1945997357",
      password: "1234",
      dateOfBirth: "11/22/2011",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [6.0, 0.3, 8.5, 4.9],
          final: 4.9,
          points: 490,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [8.2, 6.8, 10.0, 8.3],
          final: 8.3,
          points: 830,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [4.0, 9.0, 5.8, 6.3],
          final: 6.3,
          points: 630,
        },
      ],
    },
    {
      documentType: "IE",
      name: "Camila",
      lastname: "Hernandez",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1179818923",
      password: "1234",
      dateOfBirth: "12/26/2009",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [1.2, 8.3, 5.4, 5.0],
          final: 5.0,
          points: 500,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [1.6, 8.9, 7.8, 6.1],
          final: 6.1,
          points: 610,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [6.5, 2.9, 6.4, 5.3],
          final: 5.3,
          points: 530,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Luis",
      lastname: "Ramos",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1039847425",
      password: "1234",
      dateOfBirth: "6/3/2010",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [2.8, 3.3, 7.8, 4.6],
          final: 4.6,
          points: 459,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [7.9, 5.0, 3.7, 5.5],
          final: 5.5,
          points: 550,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [0.0, 8.9, 8.4, 5.8],
          final: 5.8,
          points: 580,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Sofia",
      lastname: "Hernandez",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1341758695",
      password: "1234",
      dateOfBirth: "1/13/2009",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [8.9, 3.5, 8.5, 7.0],
          final: 7.0,
          points: 700,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [9.0, 2.7, 2.6, 4.8],
          final: 4.8,
          points: 480,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [2.4, 4.1, 8.3, 4.9],
          final: 4.9,
          points: 490,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Isabel",
      lastname: "Ramos",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1185118994",
      password: "1234",
      dateOfBirth: "12/24/2010",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [2.2, 2.5, 2.2, 2.3],
          final: 2.3,
          points: 229,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [2.0, 8.0, 0.1, 3.4],
          final: 3.4,
          points: 340,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [6.1, 2.4, 0.8, 3.1],
          final: 3.1,
          points: 310,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Valentina",
      lastname: "Perez",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1315902971",
      password: "1234",
      dateOfBirth: "4/6/2010",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [2.4, 5.6, 9.2, 5.7],
          final: 5.7,
          points: 570,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [3.8, 0.6, 3.8, 2.7],
          final: 2.7,
          points: 270,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [9.0, 8.8, 9.9, 9.2],
          final: 9.2,
          points: 919,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Gabriel",
      lastname: "Perez",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1962644328",
      password: "1234",
      dateOfBirth: "6/5/2011",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [2.3, 7.5, 4.9, 4.9],
          final: 4.9,
          points: 490,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [6.7, 7.5, 8.7, 7.6],
          final: 7.6,
          points: 760,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [0.9, 3.6, 6.2, 3.6],
          final: 3.6,
          points: 360,
        },
      ],
    },
    {
      documentType: "TI",
      name: "Mateo",
      lastname: "Cardenas",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1529582447",
      password: "1234",
      dateOfBirth: "12/2/2010",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [8.8, 0.2, 5.9, 5.0],
          final: 5.0,
          points: 500,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [7.2, 5.7, 3.5, 5.5],
          final: 5.5,
          points: 550,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [1.4, 8.6, 2.3, 4.1],
          final: 4.1,
          points: 409,
        },
      ],
    },
    {
      documentType: "IE",
      name: "Lucia",
      lastname: "Perez",
      profile_img: "https://i.ibb.co/RH4HpS6/std2.jpg",
      number_identify: "1478398978",
      password: "1234",
      dateOfBirth: "3/15/2009",
      grades: [
        {
          subject: "Ciencias sociales",
          code: "101",
          grades: [6.1, 0.3, 3.5, 3.3],
          final: 3.3,
          points: 330,
        },
        {
          subject: "Lengua castellana",
          code: "102",
          grades: [1.9, 3.7, 5.2, 3.6],
          final: 3.6,
          points: 360,
        },
        {
          subject: "Matematicas",
          code: "103",
          grades: [2.3, 9.2, 3.7, 5.1],
          final: 5.1,
          points: 509,
        },
      ],
    },
  ],
};

export const authenticateStudent = (number_identify, password) => {
  const student = mockDatabase.students.find(
    (s) => s.number_identify === number_identify && s.password === password
  );
  return student || null;
};
